EBOT.Render = {
  nav() {
    const t = EBOT.I18n.t.bind(EBOT.I18n), s = EBOT.State.data;
    const locale = s.language === "en" ? "en-US" : s.language === "es" ? "es-ES" : "pt-BR";
    const now = new Date();
    const time = now.toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" });
    const date = now.toLocaleDateString(locale, { day: "2-digit", month: "short" });
    const locationLabel = `${s.currentCity || "São Paulo"}, ${s.currentState || "SP"}`;
    const neighborhood = s.currentNeighborhood || "Centro";
    const flagClass = s.language === "en" ? "flag-us" : s.language === "es" ? "flag-es" : "flag-br";
    EBOT.Utils.qs("#navbar").innerHTML = `<div class="nav-inner"><div class="brand-lockup"><div class="brand-mark">E</div><div><div class="brand-title">Ebot Explorer</div><div class="brand-sub">Tourism Totem</div></div></div><div class="nav-actions nav-actions-grouped">
      <div class="nav-primary-group"><button class="nav-btn nav-ai" data-route="aiRoute">${EBOT.Utils.icon("spark")}AI Route</button><button class="nav-btn nav-voice" data-action="voice-listen">${EBOT.Utils.icon("mic")}${t("speakEbot")}</button><button class="nav-btn" data-route="home">${EBOT.Utils.icon("home")}${t("home")}</button><button class="nav-btn" data-action="back">${EBOT.Utils.icon("back")}${t("back")}</button></div>
      <div class="nav-location-pill">${EBOT.Utils.icon("pin")}<span>${locationLabel}</span><strong>${neighborhood}</strong></div>
      <div class="nav-time-pill">${EBOT.Utils.icon("clock")}<span>${date}</span><strong>${time}</strong></div>
      <details class="language-menu"><summary class="flag-btn"><span class="flag ${flagClass}"></span>${s.language.toUpperCase()}</summary><div class="language-menu-panel"><button class="flag-btn ${s.language === "pt" ? "is-active" : ""}" data-lang="pt"><span class="flag flag-br"></span>PT</button><button class="flag-btn ${s.language === "en" ? "is-active" : ""}" data-lang="en"><span class="flag flag-us"></span>EN</button><button class="flag-btn ${s.language === "es" ? "is-active" : ""}" data-lang="es"><span class="flag flag-es"></span>ES</button></div></details>
      <details class="nav-menu"><summary class="nav-btn">${EBOT.Utils.icon("grid")}Menu</summary><div class="nav-menu-panel">
        <button class="nav-btn ${s.voiceOnly ? "is-active" : ""}" data-action="toggle-voice-mode">${EBOT.Utils.icon("mic")}${s.voiceOnly ? t("voiceOn") : t("voice")}</button>
        <button class="nav-btn" data-route="chat">${EBOT.Utils.icon("chat")}${t("chat")}</button>
        <button class="nav-btn ${s.keyboardVisible ? "is-active" : ""}" data-action="keyboard">${EBOT.Utils.icon("keyboard")}${t("keyboard")}</button>
        <button class="nav-btn" data-route="help">${EBOT.Utils.icon("help")}${t("help")}</button>
        <button class="nav-btn" data-route="accessibility">${EBOT.Utils.icon("access")}${t("accessibility")}</button>
        <button class="nav-btn" data-action="restart">${EBOT.Utils.icon("restart")}${t("restart")}</button>
      </div></details>
    </div></div>`;
  },
  screen() {
    const host = EBOT.Utils.qs("#screen"), s = EBOT.State.data;
    const renderers = { attract: this.attract, home: this.home, aiRoute: this.aiRoute, discover: this.discover, food: this.food, routes: this.routes, route: this.routeDetail, detail: this.detail, directions: this.directions, chat: this.chat, voice: this.voice, help: this.help, accessibility: this.accessibility, register: this.register, game: this.game };
    host.innerHTML = (renderers[s.screen] || this.home).call(this);
    EBOT.Utils.animateIn(host);
  },
  actionCards() {
    const t = EBOT.I18n.t.bind(EBOT.I18n);
    const cards = [
      ["discover", "exploreAttractions", "landmark", "#f97316", "Museums, parks, icons"], ["food", "findFood", "food", "#ea580c", "Restaurants and cafes"], ["discover:nearby", "nearMe", "target", "#14b8a6", "Closest suggestions"], ["discover:free", "freePlaces", "ticket", "#22c55e", "No ticket needed"], ["route:accessible-comfort", "accessibleRoute", "access", "#0ea5e9", "Comfort route"], ["chat", "talkToEbot", "chat", "#7c3aed", "Local agent"]
    ];
    return `<div class="action-grid onboarding-cards">${cards.map(([route, label, icon, color, copy]) => `<button class="action-card reveal" style="--accent:${color}" data-smart-route="${route}"><span class="icon-bubble">${EBOT.Utils.icon(icon)}</span><h3>${t(label)}</h3><p>${copy}</p></button>`).join("")}</div>`;
  },
  attractCards() {
    const cards = [
      ["aiRoute", "AI Route", "spark", "#f97316", "mirante-sol"],
      ["discover", "exploreAttractions", "landmark", "#f97316", "paco-luz"],
      ["food", "findFood", "food", "#ea580c", "mercado-central"],
      ["discover:nearby", "nearMe", "target", "#14b8a6", "parque-aurora"],
      ["discover:free", "freePlaces", "ticket", "#22c55e", "rua-das-cores"],
      ["route:accessible-comfort", "accessibleRoute", "access", "#0ea5e9", "biblioteca-viva"]
    ];
    return `<div class="attract-photo-grid">${cards.map(([route, label, icon, color, placeId]) => {
      const place = EBOT.Utils.byId(EBOT_PLACES, placeId);
      return `<button class="attract-photo-card reveal" style="--accent:${color};--photo:url('${place.image}')" data-smart-route="${route}"><span class="photo-card-icon">${EBOT.Utils.icon(icon)}</span><span class="photo-card-label">${label === "AI Route" ? "Gerar rota com AI" : EBOT.I18n.t(label)}</span><span class="photo-card-place">${EBOT.I18n.local(place.name)}</span></button>`;
    }).join("")}</div>`;
  },
  attractBot() {
    const ids = ["paco-luz", "mercado-central", "mirante-sol", "parque-aurora"];
    return `<div class="mega-bot-card assistant-card" data-state="${EBOT.State.data.assistantState}"><div class="attract-bot-map-layer">${EBOT.Map.render(ids)}</div><div class="liquid-shape shape-a"></div><div class="liquid-shape shape-b"></div><div class="bot-stage"><div class="voice-waves"><span></span><span></span><span></span></div><div class="bot" aria-hidden="true"><div class="bot-ear left"></div><div class="bot-ear right"></div><div class="bot-head"><div class="bot-face"><span class="bot-eye left"></span><span class="bot-eye right"></span><span class="bot-mouth"></span></div></div><div class="bot-arm left"></div><div class="bot-arm right"></div><div class="bot-body"><div class="bot-core"></div></div></div></div><div class="attract-floating-places">${ids.map((id, index) => { const p = EBOT.Utils.byId(EBOT_PLACES, id); return `<button class="floating-place-card fp-${index}" data-detail="${p.id}"><img src="${p.image}" alt="${EBOT.Utils.html(EBOT.I18n.local(p.name))}"/><span><strong>${EBOT.I18n.local(p.name)}</strong><small>${p.rating} ★ · ${p.neighborhood}</small></span></button>`; }).join("")}</div><div class="speech-bubble"><span class="bot-chat-loop"><span>Eu posso montar uma rota perfeita para o tempo que você tem agora.</span><span>Toque em um lugar no mapa ou fale comigo para descobrir experiências próximas.</span><span>Quer gastar pouco, comer bem ou fazer uma rota acessível? Eu guio você.</span></span></div></div>`;
  },
  attract() {
    const city = EBOT.State.data.currentCity || "sua cidade";
    return `<section class="attract-screen attract-redesign"><div class="attract-hero-dark"><div class="attract-bot-shell attract-bot-hero">${this.attractBot()}</div></div><div class="attract-command-panel"><div class="hero-content attract-welcome-panel"><p class="section-kicker">Você está em ${city}</p><h1 class="hero-title">Bem-vindo a <span class="accent">${city}</span>. O Ebot transforma sua viagem em uma rota inteligente.</h1><div class="rotating-copy"><span>Converse com nossa AI e descubra lugares que combinam com seu tempo, orçamento e vontade de explorar.</span><span>Encontre atrações, comida local, rotas acessíveis e experiências gratuitas em poucos toques.</span><span>Fale com o Ebot, receba uma rota personalizada e envie tudo para o celular por QR Code.</span></div><div class="cta-row"><button class="touch-btn primary pulse-cta" data-route="aiRoute">Gerar minha rota com AI</button><button class="touch-btn secondary" data-action="voice-listen">${EBOT.Utils.icon("mic")}${EBOT.I18n.t("speakEbot")}</button><button class="touch-btn ghost" data-route="home">Explorar opções</button></div></div>${this.attractCards()}</div></section>`;
  },
  aiRoute() {
    const prefs = EBOT.State.data.aiPrefs || {};
    const step = EBOT.State.data.aiStep || 0;
    const route = prefs.generatedRouteId ? EBOT.Utils.byId(EBOT_ROUTES, prefs.generatedRouteId) : null;
    const questions = [
      { key: "time", eyebrow: "Tempo", title: "Quanto tempo você tem agora?", copy: "Isso ajuda o Ebot a evitar uma rota longa demais para o seu momento.", options: [["quick", "Até 1 hora", "bolt"], ["half", "Meio período", "clock"], ["full", "Dia completo", "route"]], prompt: "Diga, por exemplo: tenho uma hora, meio período ou o dia todo." },
      { key: "budget", eyebrow: "Orçamento", title: "Quanto você quer gastar?", copy: "Podemos priorizar experiências gratuitas ou misturar atrações pagas.", options: [["free", "Só grátis", "ticket"], ["mixed", "Pode misturar", "card"], ["premium", "Experiência completa", "spark"]], prompt: "Você pode falar: só grátis, pode misturar ou experiência completa." },
      { key: "food", eyebrow: "Gastronomia", title: "Quer comer algo no caminho?", copy: "O Ebot pode encaixar restaurante, café ou manter a rota só de passeio.", options: [["yes", "Sim, gastronomia", "food"], ["coffee", "Só café ou doce", "cup"], ["no", "Só passear", "landmark"]], prompt: "Diga se quer gastronomia, só café ou apenas passear." },
      { key: "mood", eyebrow: "Estilo", title: "Qual clima combina com seu passeio?", copy: "Escolha uma intenção principal: conforto, fotos ou cultura.", options: [["accessible", "Confortável/acessível", "access"], ["photos", "Fotos e mirantes", "camera"], ["culture", "Cultura e história", "gallery"]], prompt: "Você pode dizer acessível, fotos bonitas ou cultura e história." },
      { key: "custom", eyebrow: "Pedido especial", title: "Quer pedir algo com suas palavras?", copy: "Exemplo: quero andar pouco, evitar lugares lotados, ver arquitetura e tomar café.", options: [], prompt: "Fale ou digite qualquer preferência especial." }
    ];
    const q = questions[Math.min(step, questions.length - 1)];
    const progress = Math.round(((step + 1) / questions.length) * 100);
    const choice = (group, value, label, icon) => `<button class="ai-choice ${prefs[group] === value ? "is-active" : ""}" data-ai-pref="${group}:${value}">${EBOT.Utils.icon(icon)}<span>${label}</span></button>`;
    const wizard = `<div class="glass-panel ai-wizard-panel reveal"><div class="ai-progress"><span style="width:${progress}%"></span></div><p class="section-kicker">Ebot AI route · ${q.eyebrow}</p><h1 class="section-title">${q.title}</h1><p class="section-copy">${q.copy}</p><div class="ai-question is-current"><div class="ai-choice-grid">${q.options.map(([value, label, icon]) => choice(q.key, value, label, icon)).join("")}</div>${q.key === "custom" ? `<div class="ai-custom-answer"><textarea data-ai-custom-input placeholder="Descreva seu passeio ideal...">${EBOT.Utils.html(prefs.customText || "")}</textarea><button class="touch-btn secondary" data-ai-save-custom="true">Salvar pedido</button></div>` : ""}</div><div class="ai-voice-panel"><button class="touch-btn primary" data-ai-voice-answer="${q.key}">${EBOT.Utils.icon("mic")}Responder por voz</button><p>${q.prompt}</p></div><div class="ai-step-actions"><button class="touch-btn ghost" data-ai-step="prev">Voltar</button>${step < questions.length - 1 ? `<button class="touch-btn primary" data-ai-step="next">Continuar</button>` : `<button class="touch-btn primary" data-ai-generate="true">${EBOT.Utils.icon("spark")}Gerar minha rota</button>`}</div></div>`;
    return `<section class="screen-grid ai-route-screen"><div class="panel-stack">${wizard}</div><div class="panel-stack">${route ? `<div class="glass-panel ai-result-card"><p class="section-kicker">Rota recomendada</p><h2 class="section-title" style="font-size:52px">${EBOT.I18n.local(route.title)}</h2><p class="section-copy">${EBOT.I18n.local(route.description)}</p>${this.routeCard(route)}${EBOT.Map.render(route.places)}</div>` : `<div class="glass-panel ai-empty-card"><p class="section-kicker">Personalização inteligente</p><h2 class="section-title" style="font-size:50px">O Ebot está ouvindo suas preferências</h2><p class="section-copy">Passe por cada pergunta. Você pode tocar nas respostas, usar voz simulada ou escrever um pedido personalizado.</p><div class="ai-summary-list"><span>Tempo: ${prefs.time || "-"}</span><span>Orçamento: ${prefs.budget || "-"}</span><span>Comida: ${prefs.food || "-"}</span><span>Estilo: ${prefs.mood || "-"}</span></div></div>`}</div></section>`;
  },
  home() {
    return `<section class="screen-grid home-screen"><div class="panel-stack"><div class="glass-panel reveal"><p class="section-kicker">Ebot Explorer</p><h1 class="section-title">${EBOT.I18n.t("dashboardTitle")}</h1><p class="section-copy">${EBOT.I18n.t("dashboardSubtitle")}</p>${this.searchBar()}${this.actionCards()}</div><div class="glass-panel reveal"><h2 class="card-title">${EBOT.I18n.t("commandExamples")}</h2><div class="tag-cloud">${EBOT.Voice.samples().map((x) => `<button class="chip" data-voice="${EBOT.Utils.html(x)}">${EBOT.Utils.icon("mic")}${EBOT.Utils.html(x)}</button>`).join("")}</div></div></div><div class="dashboard-rail home-map-rail"><div class="stat-strip"><div class="stat"><strong>20</strong><span>places</span></div><div class="stat"><strong>6</strong><span>routes</span></div><div class="stat"><strong>30</strong><span>tags</span></div></div>${EBOT.Map.render()}</div></section>`;
  },
  searchBar() { return `<form class="search-bar" data-search-form><input data-search value="${EBOT.Utils.html(EBOT.State.data.searchQuery)}" placeholder="${EBOT.I18n.t("searchPlaceholder")}" autocomplete="off" /><button class="touch-btn primary" type="submit">${EBOT.Utils.icon("search")}${EBOT.I18n.t("search")}</button></form>`; },
  tagCloud(limit) {
    const tags = EBOT_TAGS.slice(0, limit || EBOT_TAGS.length), active = EBOT.State.data.activeTags;
    return `<div class="tag-cloud">${tags.map((tag) => `<button class="chip ${active.includes(tag.id) ? "is-active" : ""}" style="--tag-color:${tag.accent}" data-tag="${tag.id}"><span class="chip-dot"></span>${EBOT.I18n.local(tag.label)}</button>`).join("")}</div>`;
  },
  filterMenus() {
    const groups = [
      ["category", "Tipo de lugar"], ["theme", "Interesses"], ["price", "Preço"], ["accessibility", "Acessibilidade"], ["food", "Comida"], ["audience", "Público"], ["duration", "Tempo"], ["mood", "Clima"]
    ];
    const active = EBOT.State.data.activeTags;
    return `<div class="filter-menu-stack">${groups.map(([group, title], index) => {
      const tags = EBOT_TAGS.filter((tag) => tag.group === group);
      if (!tags.length) return "";
      return `<details class="filter-menu" ${index < 4 ? "open" : ""}><summary><span>${title}</span><strong>${tags.filter((tag) => active.includes(tag.id)).length || tags.length}</strong></summary><div class="filter-chip-grid">${tags.map((tag) => `<button class="chip ${active.includes(tag.id) ? "is-active" : ""}" style="--tag-color:${tag.accent}" data-tag="${tag.id}"><span class="chip-dot"></span>${EBOT.I18n.local(tag.label)}</button>`).join("")}</div></details>`;
    }).join("")}</div>`;
  },
  discover(type) {
    const results = EBOT.Search.query(EBOT.State.data.searchQuery, EBOT.State.data.activeTags, type);
    return `<section class="discovery-board"><div class="glass-panel reveal discovery-filter-panel"><div class="discovery-filter-head"><div><p class="section-kicker">${EBOT.I18n.t("filters")}</p><h1 class="section-title">${type === "restaurant" ? EBOT.I18n.t("findFood") : EBOT.I18n.t("results")}</h1></div>${this.searchBar()}</div>${this.filterMenus()}</div><div class="discovery-content-row"><div class="result-stack">${results.length ? results.map((p) => this.resultCard(p)).join("") : `<div class="glass-panel"><p class="section-copy">${EBOT.I18n.t("noResults")}</p></div>`}</div><div class="map-center-panel">${EBOT.Map.render(results.slice(0, 10).map((p) => p.id))}<button class="touch-btn primary" data-route="routes">${EBOT.Utils.icon("route")}${EBOT.I18n.t("routeBuilder")}</button><button class="touch-btn secondary" data-route="aiRoute">${EBOT.Utils.icon("spark")}Gerar rota com AI</button></div></div></section>`;
  },
  food() { return this.discover("restaurant"); },
  resultCard(place) {
    return `<article class="card result-card-large reveal" data-place-card="${place.id}"><img src="${place.image}" alt="${EBOT.Utils.html(EBOT.I18n.local(place.name))}" loading="lazy"/><div class="result-card-body"><div><h3 class="card-title">${EBOT.I18n.local(place.name)}</h3><div class="card-meta"><span>${place.neighborhood}</span><span>${place.distanceKm} ${EBOT.I18n.t("km")}</span><span>${place.walkMin} ${EBOT.I18n.t("minutes")}</span><span>${place.price === "free" ? EBOT.I18n.t("free") : EBOT.I18n.t("paid")}</span></div></div><p>${EBOT.I18n.local(place.reason)}</p>${this.miniTags(place.tags.slice(0, 6))}<div class="cta-row"><button class="touch-btn primary" data-detail="${place.id}">${EBOT.I18n.t("details")}</button><button class="touch-btn ghost" data-directions="${place.id}">${EBOT.I18n.t("directions")}</button></div></div></article>`;
  },
  placeCard(place) {
    return `<article class="card place-card reveal" data-place-card="${place.id}"><img src="${place.image}" alt="${EBOT.Utils.html(EBOT.I18n.local(place.name))}" loading="lazy"/><div><h3 class="card-title">${EBOT.I18n.local(place.name)}</h3><div class="card-meta"><span>${place.neighborhood}</span><span>${place.distanceKm} ${EBOT.I18n.t("km")}</span><span>${place.walkMin} ${EBOT.I18n.t("minutes")}</span><span>${place.price === "free" ? EBOT.I18n.t("free") : EBOT.I18n.t("paid")}</span></div><p>${EBOT.I18n.local(place.reason)}</p>${this.miniTags(place.tags.slice(0, 5))}<div class="cta-row" style="margin-top:14px"><button class="touch-btn primary" data-detail="${place.id}">${EBOT.I18n.t("details")}</button><button class="touch-btn ghost" data-directions="${place.id}">${EBOT.I18n.t("directions")}</button></div></div></article>`;
  },
  miniTags(ids) { return `<div class="mini-tags">${ids.map((id) => { const tag = EBOT.Utils.byId(EBOT_TAGS, id); return tag ? `<span class="mini-tag" style="--tag-color:${tag.accent}"><i></i>${EBOT.I18n.local(tag.label)}</span>` : ""; }).join("")}</div>`; },
  routes() { return `<section class="screen-grid route-library-layout"><div class="route-library-left"><div class="glass-panel"><p class="section-kicker">Biblioteca regional</p><h1 class="section-title">Rotas prontas para explorar</h1><p class="section-copy">Coleções criadas para diferentes perfis: grátis, acessível, gastronômica, família, fotos e centro histórico.</p><div class="tag-cloud"><button class="chip is-active">Curadoria Ebot</button><button class="chip">Próximas</button><button class="chip">Até 1h</button><button class="chip">Sem custo</button></div></div><div class="route-library-grid">${EBOT_ROUTES.map((r) => this.routeLibraryCard(r)).join("")}</div></div><div class="map-center-panel route-map-panel">${EBOT.Map.render(EBOT_ROUTES.flatMap((route) => route.places).slice(0, 12))}<button class="touch-btn primary" data-route="aiRoute">${EBOT.Utils.icon("spark")}Criar rota personalizada com AI</button></div></section>`; },
  routeLibraryCard(route) {
    const hero = EBOT.Utils.byId(EBOT_PLACES, route.places[0]);
    return `<article class="card route-library-card reveal"><img src="${hero.image}" alt="${EBOT.Utils.html(EBOT.I18n.local(route.title))}" loading="lazy"/><div class="route-library-content"><p class="section-kicker">${route.type}</p><h3 class="card-title">${EBOT.I18n.local(route.title)}</h3><p>${EBOT.I18n.local(route.description)}</p><div class="card-meta"><span>${route.distanceKm} ${EBOT.I18n.t("km")}</span><span>${route.walkMin} ${EBOT.I18n.t("minutes")}</span><span>${route.accessible ? "Acessível" : "Urbana"}</span></div>${this.miniTags(route.tags)}<button class="touch-btn primary" data-route-detail="${route.id}">${EBOT.Utils.icon("route")}${EBOT.I18n.t("startRoute")}</button></div></article>`;
  },
  routeCard(route) { return `<article class="card route-card reveal"><h3 class="card-title">${EBOT.I18n.local(route.title)}</h3><p>${EBOT.I18n.local(route.description)}</p><div class="card-meta"><span>${route.distanceKm} ${EBOT.I18n.t("km")}</span><span>${route.walkMin} ${EBOT.I18n.t("minutes")}</span><span>${route.free ? EBOT.I18n.t("free") : EBOT.I18n.t("paid")}</span></div>${this.miniTags(route.tags)}<button class="touch-btn primary" data-route-detail="${route.id}">${EBOT.Utils.icon("route")}${EBOT.I18n.t("startRoute")}</button></article>`; },
  routeDetail() {
    const route = EBOT.Utils.byId(EBOT_ROUTES, EBOT.State.data.selectedRouteId) || EBOT_ROUTES[0];
    return `<section class="route-detail-layout"><div class="glass-panel route-detail-info"><p class="section-kicker">${EBOT.I18n.t("routes")}</p><h1 class="section-title">${EBOT.I18n.local(route.title)}</h1><p class="section-copy">${EBOT.I18n.local(route.description)}</p><div class="route-stops">${route.places.map((id, i) => { const p = EBOT.Utils.byId(EBOT_PLACES, id); return `<div class="route-stop"><span class="route-index">${i + 1}</span><div><strong>${EBOT.I18n.local(p.name)}</strong><p>${p.walkMin} ${EBOT.I18n.t("minutes")} · ${p.neighborhood}</p></div></div>`; }).join("")}</div><div class="cta-row"><button class="touch-btn primary" data-route="game">${EBOT.I18n.t("checkpoint")}</button><button class="touch-btn secondary" data-qr="route:${route.id}">${EBOT.I18n.t("sendToPhone")}</button></div></div><div class="route-detail-map">${EBOT.Map.render(route.places)}</div></section>`;
  },
  detail() {
    const p = EBOT.Utils.byId(EBOT_PLACES, EBOT.State.data.selectedPlaceId) || EBOT_PLACES[0];
    const gallery = [p.image, this.altImage(p, 1), this.altImage(p, 2), this.altImage(p, 3)];
    const active = EBOT.State.data.galleryIndex || 0;
    const favorite = EBOT.State.data.favorites.includes(p.id);
    return `<section class="place-detail-page"><div class="place-gallery glass-panel reveal"><div class="gallery-main"><img src="${gallery[active % gallery.length]}" alt="${EBOT.Utils.html(EBOT.I18n.local(p.name))}"/><button class="gallery-zoom" data-zoom-image="${gallery[active % gallery.length]}">Ampliar</button></div><div class="gallery-thumbs">${gallery.map((img, i) => `<button class="${i === active ? "is-active" : ""}" data-gallery-index="${i}"><img src="${img}" alt="Imagem ${i + 1}"/></button>`).join("")}</div></div><div class="glass-panel place-info-panel reveal"><p class="section-kicker">${p.neighborhood} · ${p.category}</p><h1 class="section-title">${EBOT.I18n.local(p.name)}</h1><p class="section-copy">${EBOT.I18n.local(p.reason)}</p><div class="stat-strip"><div class="stat"><strong>${p.rating}</strong><span>avaliação</span></div><div class="stat"><strong>${p.walkMin}</strong><span>${EBOT.I18n.t("minutes")}</span></div><div class="stat"><strong>${p.price === "free" ? "0" : "R$"}</strong><span>${p.price === "free" ? EBOT.I18n.t("free") : "entrada/consumo"}</span></div></div>${this.miniTags(p.tags)}<div class="detail-facts"><p><strong>${EBOT.I18n.t("openNow")}:</strong> ${p.hours}</p><p><strong>${EBOT.I18n.t("accessibility")}:</strong> ${p.accessibility.join(", ")}</p><p><strong>Por que ir:</strong> ${EBOT.I18n.local(p.tts)}</p></div><div class="cta-row"><button class="touch-btn primary" data-directions="${p.id}">${EBOT.I18n.t("directions")}</button><button class="touch-btn secondary" data-qr="place:${p.id}">${EBOT.I18n.t("sendToPhone")}</button><button class="touch-btn ghost ${favorite ? "is-active" : ""}" data-favorite="${p.id}">${favorite ? "Favorito salvo" : "Salvar favorito"}</button><button class="touch-btn ghost" data-visited="${p.id}">${EBOT.I18n.t("iWasHere")}</button></div><div class="reviews-block"><h3 class="card-title">Reviews de visitantes</h3>${this.reviews(p).map((r) => `<article class="review-card"><img src="${r.avatar}" alt="${r.name}"/><div><strong>${r.name}</strong><span>${"★".repeat(r.stars)}${"☆".repeat(5 - r.stars)}</span><p>${r.text}</p></div></article>`).join("")}</div></div></section>${EBOT.State.data.zoomImage ? `<div class="image-zoom-modal" data-action="close-zoom"><img src="${EBOT.State.data.zoomImage}" alt="Zoom"/></div>` : ""}`;
  },
  altImage(place, index) {
    const pool = ["https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1400&q=80", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80", "https://images.unsplash.com/photo-1545987796-200677ee1011?auto=format&fit=crop&w=1400&q=80", "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=80", "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1400&q=80"];
    return pool[(place.id.length + index) % pool.length];
  },
  reviews(place) {
    return [
      { name: "Marina C.", stars: 5, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80", text: "O Ebot acertou a recomendação. Foi fácil chegar e o lugar rendeu ótimas fotos." },
      { name: "Diego R.", stars: 4, avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80", text: `${EBOT.I18n.local(place.name)} vale a visita, principalmente combinando com uma rota curta pelo bairro.` },
      { name: "Lucía M.", stars: 5, avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=160&q=80", text: "Gostei das informações de acessibilidade e do QR para continuar no celular." }
    ];
  },
  directions() {
    const p = EBOT.Utils.byId(EBOT_PLACES, EBOT.State.data.selectedPlaceId) || EBOT_PLACES[0];
    return `<section class="screen-grid"><div class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("directions")}</p><h1 class="section-title">${EBOT.I18n.local(p.name)}</h1><p class="section-copy">${p.distanceKm} ${EBOT.I18n.t("km")} · ${p.walkMin} ${EBOT.I18n.t("minutes")}</p><div class="route-stops">${EBOT.Map.directions(p).map((step, i) => `<div class="route-stop"><span class="route-index">${i + 1}</span><p>${step}</p></div>`).join("")}</div><div class="cta-row"><button class="touch-btn primary" data-qr="place:${p.id}">${EBOT.I18n.t("sendToPhone")}</button><button class="touch-btn ghost" data-route="discover">${EBOT.I18n.t("results")}</button></div></div><div>${EBOT.Map.render([p.id])}</div></section>`;
  },
  chat() {
    EBOT.Chat.ensure();
    return `<section class="chat-shell"><div class="glass-panel"><div class="chat-log">${EBOT.State.data.chatMessages.map((m) => `<div class="message ${m.from}">${EBOT.Utils.html(m.text)}${m.results ? m.results.map((id) => this.placeCard(EBOT.Utils.byId(EBOT_PLACES, id))).join("") : ""}</div>`).join("")}</div><form class="chat-input" data-chat-form><input data-chat-input placeholder="${EBOT.I18n.t("searchPlaceholder")}"/><button class="touch-btn primary">${EBOT.I18n.t("search")}</button></form></div><div class="glass-panel"><h2 class="card-title">${EBOT.I18n.t("commandExamples")}</h2><div class="tag-cloud">${EBOT.Voice.samples().map((x) => `<button class="chip" data-chat-suggest="${EBOT.Utils.html(x)}">${x}</button>`).join("")}</div></div></section>`;
  },
  voice() { return `<section class="voice-screen"><div class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("voiceOnly")}</p><h1 class="section-title">${EBOT.I18n.t("speakEbot")}</h1><p class="section-copy">${EBOT.I18n.t("assistantHelp")}</p><div class="voice-orb"><button class="touch-btn primary" data-action="voice-listen">${EBOT.Utils.icon("mic")}${EBOT.I18n.t("listening")}</button></div><div class="cta-row"><button class="touch-btn ghost" data-action="toggle-voice-only">${EBOT.I18n.t("disableVoiceOnly")}</button><button class="touch-btn secondary" data-route="chat">${EBOT.I18n.t("chat")}</button></div>${this.tagCloud(12)}</div></section>`; },
  help() { return `<section class="screen-grid"><div class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("help")}</p><h1 class="section-title">${EBOT.I18n.t("howToUse")}</h1><p class="section-copy">${EBOT.I18n.t("assistantHelp")}</p>${this.actionCards()}<h2 class="card-title">${EBOT.I18n.t("privacy")}</h2><p>Local-only prototype. No login, no database, no external navigation inside the kiosk.</p></div><div>${EBOT.Map.render()}</div></section>`; },
  accessibility() { const opts = [["highContrast", "highContrast"], ["largeText", "largeText"], ["reducedMotion", "reducedMotion"], ["silentMode", "silentMode"]]; return `<section class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("accessibility")}</p><h1 class="section-title">Inclusive kiosk controls</h1><div class="action-grid">${opts.map(([key, label]) => `<button class="action-card" data-access="${key}"><span class="icon-bubble">${EBOT.Utils.icon("access")}</span><h3>${EBOT.I18n.t(label)}</h3><p>${EBOT.State.data.accessibility[key] ? "ON" : "OFF"}</p></button>`).join("")}</div></section>`; },
  register() { return `<section class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("registration")}</p><h1 class="section-title">Optional handoff</h1><form class="panel-stack" data-register-form><div class="search-bar"><input name="name" placeholder="${EBOT.I18n.t("name")}" /></div><div class="search-bar"><input name="city" placeholder="${EBOT.I18n.t("city")}" /></div><label class="chip"><input type="checkbox" name="consent" /> ${EBOT.I18n.t("consent")}</label><button class="touch-btn primary">${EBOT.I18n.t("save")}</button></form></section>`; },
  game() { const visited = EBOT.State.data.visited.length; return `<section class="screen-grid"><div class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("progress")}</p><h1 class="section-title">Explorer checkpoint</h1><p class="section-copy">${EBOT.I18n.t("badgeUnlocked")}: City Starter</p><div class="progress-track"><div class="progress-fill" style="--progress:${Math.min(100, visited * 18 + 24)}%"></div></div><div class="stat-strip"><div class="stat"><strong>${visited}</strong><span>visited</span></div><div class="stat"><strong>${EBOT.State.data.badges.length || 1}</strong><span>badges</span></div><div class="stat"><strong>QR</strong><span>${EBOT.I18n.t("checkpoint")}</span></div></div><button class="touch-btn primary" data-route="routes">${EBOT.I18n.t("routes")}</button></div><div class="progress-map-rail">${EBOT.Map.render()}</div></section>`; }
};
