EBOT.Render = {
  navCompact() {
    if (typeof window === "undefined") return false;
    if (window.innerWidth < 1280) return true;
    return false;
  },
  nav() {
    const t = EBOT.I18n.t.bind(EBOT.I18n), s = EBOT.State.data;
    const compact = this.navCompact();
    const locale = s.language === "en" ? "en-US" : s.language === "es" ? "es-ES" : "pt-BR";
    const now = new Date();
    const time = now.toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" });
    const date = now.toLocaleDateString(locale, { day: "2-digit", month: "short" });
    const locationLabel = `${s.currentCity || "São Paulo"}, ${s.currentState || "SP"}`;
    const neighborhood = s.currentNeighborhood || "Centro";
    const flagClass = s.language === "en" ? "flag-us" : s.language === "es" ? "flag-es" : "flag-br";
    const root = EBOT.Utils.qs("#navbar");
    root.classList.toggle("is-compact", compact);
    const primary = `<button class="nav-btn" data-route="home" aria-label="${EBOT.Utils.html(t("home"))}" title="${EBOT.Utils.html(t("home"))}">${EBOT.Utils.icon("home")}<span>${t("home")}</span></button><button class="nav-btn" data-action="back" aria-label="${EBOT.Utils.html(t("back"))}" title="${EBOT.Utils.html(t("back"))}">${EBOT.Utils.icon("back")}<span>${t("back")}</span></button>`;
    const secondary = `<button class="nav-btn nav-icon" data-route="chat" aria-label="${EBOT.Utils.html(t("chat"))}" title="${EBOT.Utils.html(t("chat"))}">${EBOT.Utils.icon("chat")}<span>${t("chat")}</span></button><button class="nav-btn nav-icon ${s.keyboardVisible ? "is-active" : ""}" data-action="keyboard" aria-label="${EBOT.Utils.html(t("keyboard"))}" title="${EBOT.Utils.html(t("keyboard"))}">${EBOT.Utils.icon("keyboard")}<span>${t("keyboard")}</span></button><button class="nav-btn nav-icon" data-route="help" aria-label="${EBOT.Utils.html(t("help"))}" title="${EBOT.Utils.html(t("help"))}">${EBOT.Utils.icon("help")}<span>${t("help")}</span></button><button class="nav-btn nav-icon" data-route="accessibility" aria-label="Configurações" title="Configurações">${EBOT.Utils.libIcon("settings")}<span>Configurações</span></button><button class="nav-btn nav-icon" data-action="toggle-audio" aria-label="${s.accessibility.silentMode ? "Ligar áudio" : "Desligar áudio"}" title="${s.accessibility.silentMode ? "Ligar áudio" : "Desligar áudio"}">${EBOT.Utils.icon(s.accessibility.silentMode ? "muted" : "audio")}<span>${s.accessibility.silentMode ? "Ligar áudio" : "Desligar áudio"}</span></button><button class="nav-btn nav-icon" data-action="restart" aria-label="${EBOT.Utils.html(t("restart"))}" title="${EBOT.Utils.html(t("restart"))}">${EBOT.Utils.icon("restart")}<span>${t("restart")}</span></button>`;
    const language = `<details class="language-menu"><summary class="flag-btn" aria-label="Idioma"><span class="flag ${flagClass}"></span><span class="language-code">${s.language.toUpperCase()}</span></summary><div class="language-menu-panel"><button class="flag-btn ${s.language === "pt" ? "is-active" : ""}" data-lang="pt"><span class="flag flag-br"></span>PT</button><button class="flag-btn ${s.language === "en" ? "is-active" : ""}" data-lang="en"><span class="flag flag-us"></span>EN</button><button class="flag-btn ${s.language === "es" ? "is-active" : ""}" data-lang="es"><span class="flag flag-es"></span>ES</button></div></details>`;
    const helpers = compact ? "" : `<div class="nav-context"><div class="nav-location-pill">${EBOT.Utils.icon("pin")}<span>${locationLabel}</span><strong>${neighborhood}</strong></div><div class="nav-time-pill">${EBOT.Utils.icon("clock")}<span>${date}</span><strong>${time}</strong></div></div>`;
    const more = `<details class="nav-menu"><summary class="nav-btn nav-icon" aria-label="Mais opções" title="Mais opções">${EBOT.Utils.icon("grid")}<span>Menu</span></summary><div class="nav-menu-panel">${secondary}</div></details>`;
    const aiButton = `<button class="nav-btn nav-ai" data-route="aiRoute" aria-label="Gerar rota inteligente" title="Gerar rota inteligente">${EBOT.Utils.icon("spark")}<span>Gerar rota inteligente</span></button>`;
    const assistantButton = `<button class="nav-btn nav-assistant ${s.assistantCollapsed ? "" : "is-active"}" data-action="toggle-assistant" aria-label="${s.assistantCollapsed ? "Abrir Ebot" : "Fechar Ebot"}" title="${s.assistantCollapsed ? "Abrir Ebot" : "Fechar Ebot"}"><span class="nav-assistant-icon"><img src="assets/images/Icone_explore_aplicação_1_white@4x.png" alt=""/></span><span class="nav-assistant-copy"><strong>${s.assistantCollapsed ? "Abrir Ebot" : "Fechar Ebot"}</strong><small>${s.assistantCollapsed ? "Como posso ajudar" : "Assistente aberto"}</small></span><span class="nav-assistant-orb" aria-hidden="true"></span></button>`;
    root.innerHTML = `<div class="nav-inner"><div class="brand-lockup"><div class="brand-mark">E</div><div class="brand-text"><div class="brand-title">Ebot Explorer</div><div class="brand-sub">Tourism Totem</div></div></div><div class="nav-actions">${helpers}${language}<div class="nav-primary-group">${primary}</div>${more}<div class="nav-hero-actions">${aiButton}${assistantButton}</div></div></div>`;
  },
  screen() {
    const host = EBOT.Utils.qs("#screen"), s = EBOT.State.data;
    const renderers = { attract: this.attract, home: this.home, aiRoute: this.aiRoute, discover: this.discover, food: this.food, routes: this.routes, route: this.routeDetail, detail: this.detail, directions: this.directions, chat: this.chat, voice: this.voice, help: this.help, accessibility: this.accessibility, register: this.register, game: this.game };
    host.innerHTML = (renderers[s.screen] || this.home).call(this);
    EBOT.Utils.animateIn(host);
  },
  actionCards() {
    const t = EBOT.I18n.t.bind(EBOT.I18n);
    const cards = [
      ["aiRoute", "Gerar rota inteligente", "spark", "#f97316", "Monte um roteiro pelo tempo, orçamento e estilo do passeio"], ["discover", "exploreAttractions", "landmark", "#f97316", "Museus, parques e pontos de interesse"], ["food", "findFood", "food", "#ea580c", "Restaurantes, cafés, padarias e bares"], ["discover:nearby", "nearMe", "target", "#14b8a6", "Sugestões próximas ao totem"], ["discover:free", "freePlaces", "ticket", "#22c55e", "Atrações sem ingresso"], ["route:accessible-comfort", "accessibleRoute", "access", "#0ea5e9", "Caminhos confortáveis e inclusivos"]
    ];
    return `<div class="action-grid onboarding-cards">${cards.map(([route, label, icon, color, copy]) => `<button class="action-card reveal" style="--accent:${color}" data-smart-route="${route}"><span class="icon-bubble">${EBOT.Utils.icon(icon)}</span><h3>${label.startsWith("Gerar") ? label : t(label)}</h3><p>${copy}</p></button>`).join("")}</div>`;
  },
  attractCards() {
    const cards = [
      ["aiRoute", "smartRoute", "spark", "#f97316", "mirante-sol"],
      ["discover", "exploreAttractions", "landmark", "#f97316", "paco-luz"],
      ["food", "findFood", "food", "#ea580c", "mercado-central"],
      ["discover:nearby", "nearMe", "target", "#14b8a6", "parque-aurora"],
      ["discover:free", "freePlaces", "ticket", "#22c55e", "rua-das-cores"],
      ["route:accessible-comfort", "accessibleRoute", "access", "#0ea5e9", "biblioteca-viva"]
    ];
    return `<div class="attract-photo-grid">${cards.map(([route, label, icon, color, placeId]) => {
      const place = EBOT.Utils.byId(EBOT_PLACES, placeId);
      return `<button class="attract-photo-card reveal" style="--accent:${color};--photo:url('${place.image}')" data-smart-route="${route}"><span class="photo-card-icon">${EBOT.Utils.icon(icon)}</span><span class="photo-card-label">${label === "smartRoute" ? "Gerar rota inteligente" : EBOT.I18n.t(label)}</span><span class="photo-card-place">${EBOT.I18n.local(place.name)}</span></button>`;
    }).join("")}</div>`;
  },
  attractBot() {
    const ids = ["paco-luz", "mercado-central", "mirante-sol", "parque-aurora"];
    return `<div class="mega-bot-card assistant-card" data-state="${EBOT.State.data.assistantState}"><div class="attract-bot-map-layer">${EBOT.Map.render(ids)}</div><div class="liquid-shape shape-a"></div><div class="liquid-shape shape-b"></div><div class="bot-stage"><div class="voice-waves"><span></span><span></span><span></span></div><div class="bot" aria-hidden="true"><div class="bot-ear left"></div><div class="bot-ear right"></div><div class="bot-head"><div class="bot-face"><span class="bot-eye left"></span><span class="bot-eye right"></span><span class="bot-mouth"></span></div></div><div class="bot-arm left"></div><div class="bot-arm right"></div><div class="bot-body"><div class="bot-core"></div></div></div></div><div class="attract-floating-places">${ids.map((id, index) => { const p = EBOT.Utils.byId(EBOT_PLACES, id); return `<button class="floating-place-card fp-${index}" data-detail="${p.id}"><img src="${p.image}" alt="${EBOT.Utils.html(EBOT.I18n.local(p.name))}"/><span><strong>${EBOT.I18n.local(p.name)}</strong><small>${p.rating} ★ · ${p.neighborhood}</small></span></button>`; }).join("")}</div><div class="speech-bubble"><span class="bot-chat-loop"><span>Eu posso montar uma rota inteligente para as próximas horas do seu passeio.</span><span>Escolha tempo, orçamento e clima. Depois edite as paradas antes de iniciar.</span><span>Quer gastronomia local, atrações gratuitas ou rotas acessíveis? Eu organizo o caminho.</span></span></div></div>`;
  },
  attract() {
    const city = EBOT.State.data.currentCity || "sua cidade";
    return `<section class="attract-screen attract-redesign"><div class="attract-hero-dark"><div class="attract-bot-shell attract-bot-hero">${this.attractBot()}</div></div><div class="attract-command-panel"><div class="hero-content attract-welcome-panel"><p class="section-kicker">Você está em ${city}</p><h1 class="hero-title">Gerar rota inteligente para explorar <span class="accent">${city}</span>.</h1><div class="rotating-copy"><span>Responda poucos toques e receba um roteiro ajustado ao tempo que você tem agora.</span><span>Veja opções recomendadas por perfil: gastronomia local, atrações gratuitas, perto de mim e rotas acessíveis.</span><span>Depois edite as paradas, visualize tudo no mapa e envie o roteiro por QR Code.</span></div>            <div class="cta-row"><button class="touch-btn primary pulse-cta" data-route="aiRoute">${EBOT.Utils.icon("spark")}<span>Gerar rota inteligente</span></button><button class="touch-btn secondary" data-route="home">${EBOT.Utils.icon("home")}<span>Ver opções recomendadas</span></button><button class="touch-btn ghost ebot-open-cta" data-action="open-help-with-ebot">${EBOT.Utils.icon("chat")}<span>Como posso ajudar seu passeio?</span></button></div></div>${this.attractCards()}</div></section>`;
  },
  aiRoute() {
    const prefs = EBOT.State.data.aiPrefs || {};
    const step = EBOT.State.data.aiStep || 0;
    const route = prefs.generatedRouteId ? EBOT.Utils.byId(EBOT_ROUTES, prefs.generatedRouteId) : null;
    const questions = [
      { key: "time", eyebrow: "Tempo", title: "Quanto tempo você tem agora?", copy: "Isso ajuda o Ebot a evitar uma rota longa demais para o seu momento.", options: [["quick", "Até 1 hora", "bolt"], ["half", "Meio período", "clock"], ["full", "Dia completo", "route"]] },
      { key: "budget", eyebrow: "Orçamento", title: "Quanto você quer gastar?", copy: "Podemos priorizar atrações gratuitas ou uma experiência mais completa.", options: [["free", "Só grátis", "ticket"], ["premium", "Experiência completa", "spark"]] },
      { key: "food", eyebrow: "Gastronomia", title: "Quer comer algo no caminho?", copy: "Escolha o tipo de parada gastronômica que deve entrar na rota.", options: [["yes", "Sim", "food"], ["restaurants", "Restaurantes", "utensils"], ["cafes", "Cafés", "cup"], ["bakeries", "Padarias", "bag"], ["bars", "Bares", "moon"], ["skip", "Só passar", "landmark"]] },
      { key: "mood", eyebrow: "Clima", title: "Qual clima combina com o seu passeio?", copy: "O Ebot usa essa intenção para ajustar as paradas recomendadas.", options: [["accessible", "Acessível", "access"], ["outdoor", "Ao ar livre", "sun"], ["park", "Parques", "leaf"], ["lake", "Lagos", "wave"], ["waterfall", "Cachoeiras", "wave"], ["beach", "Praias", "sun"], ["view", "Mirantes", "mountain"], ["historic", "Locais históricos", "landmark"]] }
    ];
    const q = questions[Math.min(step, questions.length - 1)];
    const progress = Math.round(((step + 1) / questions.length) * 100);
    const choice = (group, value, label, icon) => `<button class="ai-choice ${prefs[group] === value ? "is-active" : ""}" data-ai-pref="${group}:${value}">${EBOT.Utils.icon(icon)}<span>${label}</span></button>`;
    const wizard = `<div class="glass-panel ai-wizard-panel reveal"><div class="ai-progress"><span style="width:${progress}%"></span></div><p class="section-kicker">Gerar rota inteligente · ${q.eyebrow}</p><h1 class="section-title">${q.title}</h1><p class="section-copy">${q.copy}</p><div class="ai-question is-current"><div class="ai-choice-grid ai-choice-count-${q.options.length}">${q.options.map(([value, label, icon]) => choice(q.key, value, label, icon)).join("")}</div></div><div class="ai-step-actions"><button class="touch-btn ghost" data-ai-step="prev">Voltar</button>${step < questions.length - 1 ? `<button class="touch-btn primary" data-ai-step="next">Continuar</button>` : `<button class="touch-btn primary" data-ai-generate="true">${EBOT.Utils.icon("spark")}Gerar rota inteligente</button>`}</div></div>`;
    const empty = `<div class="glass-panel ai-empty-card"><p class="section-kicker">Personalização inteligente</p><h2 class="section-title ai-panel-title">Responda as opções para montar sua rota.</h2><p class="section-copy">Depois da recomendação, você poderá incluir ou remover atrações antes de iniciar o passeio.</p><div class="ai-summary-list"><span>Tempo: ${prefs.time || "-"}</span><span>Orçamento: ${prefs.budget || "-"}</span><span>Comida: ${prefs.food || "-"}</span><span>Clima: ${prefs.mood || "-"}</span></div></div>`;
    if (route) return `<section class="ai-route-generated">${this.aiRouteResult(route)}</section>`;
    return `<section class="screen-grid ai-route-screen"><div class="panel-stack">${wizard}</div><div class="panel-stack">${empty}</div></section>`;
  },
  aiRouteResult(route) {
    const s = EBOT.State.data;
    const routeIds = (s.routeDraft && s.routeDraft.length ? s.routeDraft : route.places).filter((id) => EBOT.Utils.byId(EBOT_PLACES, id));
    const routePlaces = routeIds.map((id) => EBOT.Utils.byId(EBOT_PLACES, id)).filter(Boolean);
    const previewIds = s.aiMapMode === "all" ? this.aiCompatiblePlaceIds(routeIds) : routeIds;
    const routeMeta = s.routeDraftMeta || {};
    const routeTitle = routeMeta.title || EBOT.I18n.local(route.title);
    const routeDescription = routeMeta.description || EBOT.I18n.local(route.description);
    const totalWalk = routePlaces.reduce((sum, place) => sum + place.walkMin, 0);
    const totalKm = routePlaces.reduce((sum, place) => sum + place.distanceKm, 0).toFixed(1);
    const summary = `<aside class="ai-route-side"><div class="ai-route-summary"><div><p class="section-kicker">Rota recomendada</p><h2>${EBOT.Utils.html(routeTitle)}</h2><p>${EBOT.Utils.html(routeDescription)}</p></div><div class="ai-route-stats compact"><span><strong>${routePlaces.length}</strong> paradas</span><span><strong>${totalKm}</strong> km</span><span><strong>${totalWalk}</strong> min</span></div><div class="route-editor-actions"><button class="touch-btn ghost" data-ai-edit-prefs="true">Refazer</button><button class="touch-btn secondary" data-route-meta-open="true">${EBOT.Utils.libIcon("pencil")}Editar texto</button><button class="touch-btn secondary" data-route-save="true">${EBOT.Utils.libIcon("save")}Salvar</button><button class="touch-btn primary" data-route-start-draft="true">${EBOT.I18n.t("startRoute")}</button></div></div>${this.aiRouteEditor(routePlaces, route)}</aside>`;
    return `<div class="glass-panel ai-result-card ai-result-expanded"><div class="ai-generated-body ai-generated-body-priority"><div class="ai-generated-map">${EBOT.Map.render(previewIds, route.id, routeIds)}</div>${summary}</div>${this.routeMetaModal(routeTitle, routeDescription)}</div>`;
  },
  aiCompatiblePlaceIds(routeIds) {
    const prefs = EBOT.State.data.aiPrefs || {};
    const tags = [prefs.budget === "free" ? "free" : null, { yes: "food", restaurants: "food", cafes: "coffee", bakeries: "bakery", bars: "bar" }[prefs.food], { accessible: "accessible", outdoor: "outdoor", park: "park", lake: "lake", waterfall: "waterfall", beach: "beach", view: "view", historic: "historic" }[prefs.mood]].filter(Boolean);
    const matches = tags.length ? EBOT_PLACES.filter((place) => tags.some((tag) => place.tags.includes(tag))).map((place) => place.id) : [];
    return Array.from(new Set(routeIds.concat(matches.length ? matches : EBOT_PLACES.map((place) => place.id)))).slice(0, 14);
  },
  aiRouteEditor(routePlaces, route) {
    const query = EBOT.State.data.routeSearchQuery || "";
    const selected = new Set(routePlaces.map((place) => place.id));
    const suggestions = (query ? EBOT.Search.query(query, [], null) : EBOT_PLACES.slice(0, 8)).filter((place) => !selected.has(place.id)).slice(0, 6);
    return `<div class="ai-route-editor"><div class="ai-route-editor-head compact"><div><p class="section-kicker">Paradas</p><h3 class="card-title">Reorganize a rota</h3></div></div><div class="route-draft-list">${routePlaces.map((place, index) => `<article class="route-draft-item" draggable="true" data-route-drag="${place.id}" data-route-drop="${place.id}"><span class="route-drag-handle" aria-hidden="true">⋮⋮</span><span class="route-index">${index + 1}</span><div><strong>${EBOT.I18n.local(place.name)}</strong><p>${place.neighborhood} · ${place.walkMin} ${EBOT.I18n.t("minutes")}</p></div><button class="touch-btn ghost" data-route-remove="${place.id}">Remover</button></article>`).join("")}</div><div class="route-place-search"><form class="search-bar" data-route-search-form><input data-route-search value="${EBOT.Utils.html(query)}" placeholder="Buscar locais para incluir na rota" autocomplete="off"/><button class="touch-btn secondary" type="submit">${EBOT.Utils.icon("search")}Buscar</button></form><div class="route-search-results">${suggestions.map((place) => `<article class="route-search-item"><img src="${place.image}" alt="${EBOT.Utils.html(EBOT.I18n.local(place.name))}"/><div><strong>${EBOT.I18n.local(place.name)}</strong><p>${place.neighborhood} · ${place.walkMin} ${EBOT.I18n.t("minutes")}</p></div><button class="touch-btn secondary" data-route-add="${place.id}">Adicionar</button></article>`).join("") || `<p class="section-copy">Nenhum local disponível para adicionar.</p>`}</div></div></div>`;
  },
  routeMetaModal(title, description) {
    if (!EBOT.State.data.routeMetaModalOpen) return "";
    return `<div class="route-meta-modal-layer" data-route-meta-backdrop><div class="route-meta-modal" role="dialog" aria-modal="true" aria-labelledby="route-meta-title"><button class="modal-close-btn" data-route-meta-close="true" aria-label="Fechar">${EBOT.Utils.libIcon("x")}</button><p class="section-kicker">Editar apresentação</p><h2 id="route-meta-title">Nome e descrição da rota</h2><p>Essas informações ficam salvas temporariamente neste totem.</p><label><span>Nome da rota</span><input data-route-title value="${EBOT.Utils.html(title)}" maxlength="72"/></label><label><span>Descrição</span><textarea data-route-desc maxlength="220">${EBOT.Utils.html(description)}</textarea></label><div class="modal-action-row"><button class="touch-btn ghost" data-route-meta-close="true">Cancelar</button><button class="touch-btn primary" data-route-meta-save="true">${EBOT.Utils.libIcon("save")}Salvar texto</button></div></div></div>`;
  },
  home() {
    return `<section class="screen-grid home-screen"><div class="panel-stack"><div class="glass-panel reveal"><p class="section-kicker">Ebot Explorer</p><h1 class="section-title">${EBOT.I18n.t("dashboardTitle")}</h1><p class="section-copy">${EBOT.I18n.t("dashboardSubtitle")}</p>${this.searchBar()}${this.actionCards()}</div><div class="glass-panel reveal"><h2 class="card-title">${EBOT.I18n.t("commandExamples")}</h2><div class="tag-cloud">${EBOT.Voice.samples().map((x) => `<button class="chip" data-voice="${EBOT.Utils.html(x)}">${EBOT.Utils.icon("mic")}${EBOT.Utils.html(x)}</button>`).join("")}</div></div></div><div class="dashboard-rail home-map-rail"><div class="stat-strip"><div class="stat"><strong>${EBOT_PLACES.length}</strong><span>places</span></div><div class="stat"><strong>${EBOT_ROUTES.length}</strong><span>routes</span></div><div class="stat"><strong>${EBOT_TAGS.length}</strong><span>tags</span></div></div>${EBOT.Map.render()}</div></section>`;
  },
  searchBar() { return `<form class="search-bar" data-search-form><input data-search value="${EBOT.Utils.html(EBOT.State.data.searchQuery)}" placeholder="${EBOT.I18n.t("searchPlaceholder")}" autocomplete="off" /><button class="touch-btn primary" type="submit">${EBOT.Utils.icon("search")}${EBOT.I18n.t("search")}</button></form>`; },
  tagCloud(limit) {
    const tags = EBOT_TAGS.slice(0, limit || EBOT_TAGS.length), active = EBOT.State.data.activeTags;
    return `<div class="tag-cloud">${tags.map((tag) => `<button class="chip ${active.includes(tag.id) ? "is-active" : ""}" style="--tag-color:${tag.accent}" data-tag="${tag.id}"><span class="chip-dot"></span>${EBOT.I18n.local(tag.label)}</button>`).join("")}</div>`;
  },
  filterMenus() {
    const groups = [
      ["category", "Tipo de lugar"], ["theme", "Interesses"], ["price", "Preço"], ["accessibility", "Acessibilidade"], ["food", "Comida"], ["audience", "Público"], ["duration", "Tempo"], ["mood", "Clima"]
    ];
    const active = EBOT.State.data.activeTags;
    return `<div class="filter-menu-stack">${groups.map(([group, title], index) => {
      const tags = EBOT_TAGS.filter((tag) => tag.group === group);
      if (!tags.length) return "";
      return `<details class="filter-menu" ${index < 4 ? "open" : ""}><summary><span>${title}</span><strong>${tags.filter((tag) => active.includes(tag.id)).length || tags.length}</strong></summary><div class="filter-chip-grid">${tags.map((tag) => `<button class="chip ${active.includes(tag.id) ? "is-active" : ""}" style="--tag-color:${tag.accent}" data-tag="${tag.id}"><span class="chip-dot"></span>${EBOT.I18n.local(tag.label)}</button>`).join("")}</div></details>`;
    }).join("")}</div>`;
  },
  discover(type) {
    const results = EBOT.Search.query(EBOT.State.data.searchQuery, EBOT.State.data.activeTags, type);
    return `<section class="discovery-board"><div class="glass-panel reveal discovery-filter-panel"><div class="discovery-filter-head"><div><p class="section-kicker">${EBOT.I18n.t("filters")}</p><h1 class="section-title">${type === "restaurant" ? EBOT.I18n.t("findFood") : EBOT.I18n.t("results")}</h1></div>${this.searchBar()}</div>${this.filterMenus()}</div><div class="discovery-content-row"><div class="result-stack">${results.length ? results.map((p) => this.resultCard(p)).join("") : `<div class="glass-panel"><p class="section-copy">${EBOT.I18n.t("noResults")}</p></div>`}</div><div class="map-center-panel">${EBOT.Map.render(results.slice(0, 10).map((p) => p.id))}<button class="touch-btn primary" data-route="routes">${EBOT.Utils.icon("route")}${EBOT.I18n.t("routeBuilder")}</button><button class="touch-btn secondary" data-route="aiRoute">${EBOT.Utils.icon("spark")}Gerar rota inteligente</button></div></div></section>`;
  },
  food() { return this.discover("restaurant"); },
  resultCard(place) {
    return `<article class="card result-card-large reveal" data-place-card="${place.id}"><img src="${place.image}" alt="${EBOT.Utils.html(EBOT.I18n.local(place.name))}" loading="lazy"/><div class="result-card-body"><div><h3 class="card-title">${EBOT.I18n.local(place.name)}</h3><div class="card-meta"><span>${place.neighborhood}</span><span>${place.distanceKm} ${EBOT.I18n.t("km")}</span><span>${place.walkMin} ${EBOT.I18n.t("minutes")}</span><span>${place.price === "free" ? EBOT.I18n.t("free") : EBOT.I18n.t("paid")}</span></div></div><p>${EBOT.I18n.local(place.reason)}</p>${this.miniTags(place.tags.slice(0, 6))}<div class="cta-row"><button class="touch-btn primary" data-detail="${place.id}">${EBOT.I18n.t("details")}</button><button class="touch-btn ghost" data-directions="${place.id}">${EBOT.I18n.t("directions")}</button></div></div></article>`;
  },
  placeCard(place) {
    return `<article class="card place-card reveal" data-place-card="${place.id}"><img src="${place.image}" alt="${EBOT.Utils.html(EBOT.I18n.local(place.name))}" loading="lazy"/><div><h3 class="card-title">${EBOT.I18n.local(place.name)}</h3><div class="card-meta"><span>${place.neighborhood}</span><span>${place.distanceKm} ${EBOT.I18n.t("km")}</span><span>${place.walkMin} ${EBOT.I18n.t("minutes")}</span><span>${place.price === "free" ? EBOT.I18n.t("free") : EBOT.I18n.t("paid")}</span></div><p>${EBOT.I18n.local(place.reason)}</p>${this.miniTags(place.tags.slice(0, 5))}<div class="cta-row" style="margin-top:14px"><button class="touch-btn primary" data-detail="${place.id}">${EBOT.I18n.t("details")}</button><button class="touch-btn ghost" data-directions="${place.id}">${EBOT.I18n.t("directions")}</button></div></div></article>`;
  },
  miniTags(ids) { return `<div class="mini-tags">${ids.map((id) => { const tag = EBOT.Utils.byId(EBOT_TAGS, id); return tag ? `<span class="mini-tag" style="--tag-color:${tag.accent}"><i></i>${EBOT.I18n.local(tag.label)}</span>` : ""; }).join("")}</div>`; },
  routes() { return `<section class="screen-grid route-library-layout"><div class="route-library-left"><div class="glass-panel"><p class="section-kicker">Biblioteca regional</p><h1 class="section-title">Rotas prontas para explorar</h1><p class="section-copy">Coleções criadas para diferentes perfis: grátis, acessível, gastronômica, família, fotos e centro histórico.</p><div class="tag-cloud"><button class="chip is-active">Curadoria Ebot</button><button class="chip">Próximas</button><button class="chip">Até 1h</button><button class="chip">Sem custo</button></div></div><div class="route-library-grid">${EBOT_ROUTES.map((r) => this.routeLibraryCard(r)).join("")}</div></div><div class="map-center-panel route-map-panel">${EBOT.Map.render(EBOT_ROUTES.flatMap((route) => route.places).slice(0, 12))}<button class="touch-btn primary" data-route="aiRoute">${EBOT.Utils.icon("spark")}Gerar rota inteligente</button></div></section>`; },
  routeLibraryCard(route) {
    const hero = EBOT.Utils.byId(EBOT_PLACES, route.places[0]);
    return `<article class="card route-library-card reveal"><img src="${hero.image}" alt="${EBOT.Utils.html(EBOT.I18n.local(route.title))}" loading="lazy"/><div class="route-library-content"><p class="section-kicker">${route.type}</p><h3 class="card-title">${EBOT.I18n.local(route.title)}</h3><p>${EBOT.I18n.local(route.description)}</p><div class="card-meta"><span>${route.distanceKm} ${EBOT.I18n.t("km")}</span><span>${route.walkMin} ${EBOT.I18n.t("minutes")}</span><span>${route.accessible ? "Acessível" : "Urbana"}</span></div>${this.miniTags(route.tags)}<button class="touch-btn primary" data-route-detail="${route.id}">${EBOT.Utils.icon("route")}${EBOT.I18n.t("startRoute")}</button></div></article>`;
  },
  routeCard(route) { return `<article class="card route-card reveal"><h3 class="card-title">${EBOT.I18n.local(route.title)}</h3><p>${EBOT.I18n.local(route.description)}</p><div class="card-meta"><span>${route.distanceKm} ${EBOT.I18n.t("km")}</span><span>${route.walkMin} ${EBOT.I18n.t("minutes")}</span><span>${route.free ? EBOT.I18n.t("free") : EBOT.I18n.t("paid")}</span></div>${this.miniTags(route.tags)}<button class="touch-btn primary" data-route-detail="${route.id}">${EBOT.Utils.icon("route")}${EBOT.I18n.t("startRoute")}</button></article>`; },
  routeDetail() {
    const route = EBOT.Utils.byId(EBOT_ROUTES, EBOT.State.data.selectedRouteId) || EBOT_ROUTES[0];
    const routeIds = EBOT.State.data.routeDraftSourceId === route.id && EBOT.State.data.routeDraft.length ? EBOT.State.data.routeDraft : route.places;
    const routeMeta = EBOT.State.data.routeDraftSourceId === route.id ? EBOT.State.data.routeDraftMeta || {} : {};
    const title = routeMeta.title || EBOT.I18n.local(route.title);
    const description = routeMeta.description || `${title} editada com ${routeIds.length} paradas para este passeio.`;
    return `<section class="route-detail-layout"><div class="glass-panel route-detail-info"><p class="section-kicker">${EBOT.I18n.t("routes")}</p><h1 class="section-title">${EBOT.Utils.html(title)}</h1><p class="section-copy">${EBOT.Utils.html(description)}</p><div class="route-stops">${routeIds.map((id, i) => { const p = EBOT.Utils.byId(EBOT_PLACES, id); return p ? `<div class="route-stop"><span class="route-index">${i + 1}</span><div><strong>${EBOT.I18n.local(p.name)}</strong><p>${p.walkMin} ${EBOT.I18n.t("minutes")} · ${p.neighborhood}</p></div></div>` : ""; }).join("")}</div><div class="cta-row"><button class="touch-btn primary" data-route="game">${EBOT.I18n.t("checkpoint")}</button><button class="touch-btn secondary" data-qr="route:${route.id}">${EBOT.I18n.t("sendToPhone")}</button></div></div><div class="route-detail-map">${EBOT.Map.render(routeIds, route.id, routeIds)}</div></section>`;
  },
    detail() {
    const p = EBOT.Utils.byId(EBOT_PLACES, EBOT.State.data.selectedPlaceId) || EBOT_PLACES[0];
    const gallery = [p.image, this.altImage(p, 1), this.altImage(p, 2), this.altImage(p, 3)];
    const active = EBOT.State.data.galleryIndex || 0;
    const favorite = EBOT.State.data.favorites.includes(p.id);
    return `<section class="place-detail-page"><div class="place-gallery glass-panel reveal"><div class="gallery-main"><img src="${gallery[active % gallery.length]}" alt="${EBOT.Utils.html(EBOT.I18n.local(p.name))}"/><button class="gallery-zoom" data-action="open-gallery">Ampliar</button></div><div class="gallery-thumbs">${gallery.map((img, i) => `<button class="${i === active ? "is-active" : ""}" data-gallery-index="${i}"><img src="${img}" alt="Imagem ${i + 1}"/></button>`).join("")}</div></div><div class="glass-panel place-info-panel reveal"><p class="section-kicker">${p.neighborhood} · ${p.category}</p><h1 class="section-title">${EBOT.I18n.local(p.name)}</h1><p class="section-copy">${EBOT.I18n.local(p.reason)}</p><div class="stat-strip"><div class="stat"><strong>${p.rating}</strong><span>avaliação</span></div><div class="stat"><strong>${p.walkMin}</strong><span>${EBOT.I18n.t("minutes")}</span></div><div class="stat"><strong>${p.price === "free" ? "0" : "R$"}</strong><span>${p.price === "free" ? EBOT.I18n.t("free") : "entrada/consumo"}</span></div></div>${this.miniTags(p.tags)}<div class="detail-facts"><p><strong>${EBOT.I18n.t("openNow")}:</strong> ${p.hours}</p><p><strong>${EBOT.I18n.t("accessibility")}:</strong> ${p.accessibility.join(", ")}</p><p><strong>Por que ir:</strong> ${EBOT.I18n.local(p.tts)}</p></div><div class="cta-row"><button class="touch-btn primary" data-directions="${p.id}">${EBOT.I18n.t("directions")}</button><button class="touch-btn secondary" data-qr="place:${p.id}">${EBOT.I18n.t("sendToPhone")}</button><button class="touch-btn ghost ${favorite ? "is-active" : ""}" data-favorite="${p.id}">${favorite ? "Favorito salvo" : "Salvar favorito"}</button><button class="touch-btn ghost" data-visited="${p.id}">${EBOT.I18n.t("iWasHere")}</button></div><div class="reviews-block"><h3 class="card-title">Reviews de visitantes</h3>${this.reviews(p).map((r) => `<article class="review-card"><img src="${r.avatar}" alt="${r.name}"/><div><strong>${r.name}</strong><p>${r.text}</p></div></article>`).join("")}</div></div>${this.galleryModal(p)}</section>`;
  },
  galleryModal(p) {
    if (!EBOT.State.data.galleryOpen) return "";
    const gallery = [p.image, this.altImage(p, 1), this.altImage(p, 2), this.altImage(p, 3)];
    const active = EBOT.State.data.galleryIndex || 0;
    const safe = active % gallery.length;
    const src = gallery[safe];
    const zoom = EBOT.State.data.galleryZoom || 1;
    return `<div class="gallery-modal-layer" data-gallery-backdrop="true" role="dialog" aria-modal="true" aria-label="Galeria de imagens"><button class="gallery-modal-close" data-gallery-close="true" aria-label="Fechar">${EBOT.Utils.libIcon("x")}</button><div class="gallery-modal-stage"><button class="gallery-nav gallery-prev" data-gallery-prev="true" aria-label="Imagem anterior" ${safe === 0 ? "disabled" : ""}>${EBOT.Utils.libIcon("chevron-left")}</button><div class="gallery-modal-frame" data-gallery-frame="true"><img src="${src}" alt="${EBOT.Utils.html(EBOT.I18n.local(p.name))}" style="transform:scale(${zoom})"/></div><button class="gallery-nav gallery-next" data-gallery-next="true" aria-label="Próxima imagem" ${safe === gallery.length - 1 ? "disabled" : ""}>${EBOT.Utils.libIcon("chevron-right")}</button></div><div class="gallery-modal-bar"><div class="gallery-dots">${gallery.map((_, i) => `<button class="${i === safe ? "is-active" : ""}" data-gallery-index="${i}" aria-label="Imagem ${i + 1}"></button>`).join("")}</div><div class="gallery-zoom-controls"><button class="touch-btn ghost" data-gallery-zoom="out" aria-label="Diminuir zoom" ${zoom <= 1 ? "disabled" : ""}>${EBOT.Utils.libIcon("minus")}</button><span>${Math.round(zoom * 100)}%</span><button class="touch-btn ghost" data-gallery-zoom="in" aria-label="Aumentar zoom" ${zoom >= 3 ? "disabled" : ""}>${EBOT.Utils.libIcon("plus")}</button></div></div><div class="gallery-modal-caption"><strong>${EBOT.Utils.html(EBOT.I18n.local(p.name))}</strong><span>Imagem ${safe + 1} de ${gallery.length}</span></div></div>`;
  },
  altImage(place, index) {
    const pool = ["https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1400&q=80", "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80", "https://images.unsplash.com/photo-1545987796-200677ee1011?auto=format&fit=crop&w=1400&q=80", "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=80", "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1400&q=80"];
    return pool[(place.id.length + index) % pool.length];
  },
  selectedPlaceGallery() {
    const p = EBOT.Utils.byId(EBOT_PLACES, EBOT.State.data.selectedPlaceId) || EBOT_PLACES[0];
    return [p.image, this.altImage(p, 1), this.altImage(p, 2), this.altImage(p, 3)];
  },
  reviews(place) {
    return [
      { name: "Marina C.", stars: 5, avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80", text: "O Ebot acertou a recomendação. Foi fácil chegar e o lugar rendeu ótimas fotos." },
      { name: "Diego R.", stars: 4, avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80", text: `${EBOT.I18n.local(place.name)} vale a visita, principalmente combinando com uma rota curta pelo bairro.` },
      { name: "Lucía M.", stars: 5, avatar: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=160&q=80", text: "Gostei das informações de acessibilidade e do QR para continuar no celular." }
    ];
  },
  directions() {
    const p = EBOT.Utils.byId(EBOT_PLACES, EBOT.State.data.selectedPlaceId) || EBOT_PLACES[0];
    return `<section class="screen-grid"><div class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("directions")}</p><h1 class="section-title">${EBOT.I18n.local(p.name)}</h1><p class="section-copy">${p.distanceKm} ${EBOT.I18n.t("km")} · ${p.walkMin} ${EBOT.I18n.t("minutes")}</p><div class="route-stops">${EBOT.Map.directions(p).map((step, i) => `<div class="route-stop"><span class="route-index">${i + 1}</span><p>${step}</p></div>`).join("")}</div><div class="cta-row"><button class="touch-btn primary" data-qr="place:${p.id}">${EBOT.I18n.t("sendToPhone")}</button><button class="touch-btn ghost" data-route="discover">${EBOT.I18n.t("results")}</button></div></div><div>${EBOT.Map.render([p.id])}</div></section>`;
  },
  chat() {
    EBOT.Chat.ensure();
    return `<section class="chat-shell"><div class="glass-panel"><div class="chat-log">${EBOT.State.data.chatMessages.map((m) => `<div class="message ${m.from}">${EBOT.Utils.html(m.text)}${m.results ? m.results.map((id) => this.placeCard(EBOT.Utils.byId(EBOT_PLACES, id))).join("") : ""}</div>`).join("")}</div><form class="chat-input" data-chat-form><input data-chat-input placeholder="${EBOT.I18n.t("searchPlaceholder")}"/><button class="touch-btn primary">${EBOT.I18n.t("search")}</button></form></div><div class="glass-panel"><h2 class="card-title">${EBOT.I18n.t("commandExamples")}</h2><div class="tag-cloud">${EBOT.Voice.samples().map((x) => `<button class="chip" data-chat-suggest="${EBOT.Utils.html(x)}">${x}</button>`).join("")}</div></div></section>`;
  },
  voice() { return `<section class="voice-screen"><div class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("voiceOnly")}</p><h1 class="section-title">${EBOT.I18n.t("speakEbot")}</h1><p class="section-copy">${EBOT.I18n.t("assistantHelp")}</p><div class="voice-orb"><button class="touch-btn primary" data-action="voice-listen">${EBOT.Utils.icon("mic")}${EBOT.I18n.t("listening")}</button></div><div class="cta-row"><button class="touch-btn ghost" data-action="toggle-voice-only">${EBOT.I18n.t("disableVoiceOnly")}</button><button class="touch-btn secondary" data-route="chat">${EBOT.I18n.t("chat")}</button></div>${this.tagCloud(12)}</div></section>`; },
  help() { return `<section class="screen-grid"><div class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("help")}</p><h1 class="section-title">${EBOT.I18n.t("howToUse")}</h1><p class="section-copy">${EBOT.I18n.t("assistantHelp")}</p>${this.actionCards()}<h2 class="card-title">${EBOT.I18n.t("privacy")}</h2><p>Local-only prototype. No login, no database, no external navigation inside the kiosk.</p></div><div>${EBOT.Map.render()}</div></section>`; },
  accessibility() { const opts = [["highContrast", "highContrast", "access"], ["largeText", "largeText", "settings"], ["reducedMotion", "reducedMotion", "layers"], ["silentMode", "silentMode", EBOT.State.data.accessibility.silentMode ? "muted" : "audio"]]; return `<section class="glass-panel"><p class="section-kicker">Configurações</p><h1 class="section-title">Ajustes do totem</h1><p class="section-copy">Controle áudio, leitura visual, contraste e movimento da interface.</p><div class="action-grid">${opts.map(([key, label, icon]) => `<button class="action-card" data-access="${key}"><span class="icon-bubble">${EBOT.Utils.icon(icon)}</span><h3>${EBOT.I18n.t(label)}</h3><p>${EBOT.State.data.accessibility[key] ? "Ativado" : "Desativado"}</p></button>`).join("")}</div></section>`; },
  register() { return `<section class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("registration")}</p><h1 class="section-title">Optional handoff</h1><form class="panel-stack" data-register-form><div class="search-bar"><input name="name" placeholder="${EBOT.I18n.t("name")}" /></div><div class="search-bar"><input name="city" placeholder="${EBOT.I18n.t("city")}" /></div><label class="chip"><input type="checkbox" name="consent" /> ${EBOT.I18n.t("consent")}</label><button class="touch-btn primary">${EBOT.I18n.t("save")}</button></form></section>`; },
  game() { const visited = EBOT.State.data.visited.length; return `<section class="screen-grid"><div class="glass-panel"><p class="section-kicker">${EBOT.I18n.t("progress")}</p><h1 class="section-title">Explorer checkpoint</h1><p class="section-copy">${EBOT.I18n.t("badgeUnlocked")}: City Starter</p><div class="progress-track"><div class="progress-fill" style="--progress:${Math.min(100, visited * 18 + 24)}%"></div></div><div class="stat-strip"><div class="stat"><strong>${visited}</strong><span>visited</span></div><div class="stat"><strong>${EBOT.State.data.badges.length || 1}</strong><span>badges</span></div><div class="stat"><strong>QR</strong><span>${EBOT.I18n.t("checkpoint")}</span></div></div><button class="touch-btn primary" data-route="routes">${EBOT.I18n.t("routes")}</button></div><div class="progress-map-rail">${EBOT.Map.render()}</div></section>`; }
};
